### ISSUE TITLE
proper 1.1 won't build with Erlang 18

### ISSUE THREAD

**Issue by voila** [manopapad/proper#100]
with: Erlang/OTP 18 [erts-7.0]

proper$ make
./rebar get-deps
==> proper (get-deps)
./rebar compile
==> proper (compile)
make[1]: `include/compile_flags.hrl' is up to date.
Compiled src/proper_prop_remover.erl
src/proper_transformer.erl:56: type dict() undefined
make: *** [compile] Error 1

**Comment by eproxus** [comment]
I second this. Another tagged release version would be nice.

**Comment by exterm** [comment]
I also have this problem. Please tag another release. Thanks for your work!

**Comment by kostis** [comment]
We have one more pending issue with 18.x having to do with the automatic generation of terms from ADTs which are declared `opaque`.  Once this has been resolved, we'll tag a new version.

**Comment by ibnfirnas** [comment]
:+1:

**Comment by djnym** [comment]
Any updates on this?

**Comment by eproxus** [comment]
@djnym Master does build on Erlang 18+, but it would be nice with a tagged version.

**Comment by rbarlow** [comment]
Hello!

I am the Fedora package maintainer for this package, and the current version (1.1) fails to build in Rawhide which recently updated to Erlang 18. Next Tuesday (Feb. 23) is when Fedora 24 branches from Rawhide so I need to fix the build failure before then. I can fix it by backporting the patches that have gone onto the master branch, but I'd love to fix it by updating to a tagged release.

Would you consider making a tagged release very soon?

**Comment by kostis** [comment]
There is a new tagged version of PropEr: https://github.com/manopapad/proper/releases

Enjoy!
