### ISSUE TITLE
2 failing tests on Erlang/OTP 18.0/18.1

### ISSUE THREAD

**Issue by ifn** [manopapad/proper#107]
[root@fb5898e01c12 proper]# make tests
./rebar compile
==> proper (compile)
make[1]: Entering directory `/tmp/proper'
make[1]: `include/compile_flags.hrl' is up to date.
make[1]: Leaving directory `/tmp/proper'
./rebar eunit
==> proper (eunit)
proper_tests:1033: adts_test_...*failed*
in function proper_tests:'-adts_test_/0-fun-1-'/0 (test/proper_tests.erl, line 1033)
in call from proper_tests:'-adts_test_/0-fun-6-'/0 (test/proper_tests.erl, line 1033)
**error:{assertMatch,[{module,proper_tests},
              {line,1033},
              {expression,"proper : quickcheck ( ? FORALL ( { X , S } , { integer ( ) , set ( ) } , sets : is_element ( X , sets : add_element ( X , S ) ) ) , [ 20 ] )"},
              {pattern,"true"},
              {value,false}]}
  output:<<"!
Failed: After 1 test(s).
An exception was raised: error:badarg.
Stacktrace: [{sets,on_bucket,3,[{file,"sets.erl"},{line,284}]},
             {sets,add_element,2,[{file,"sets.erl"},{line,131}]}].
{0,{set,0,0,9,0,1,1,{[]},{'\201'}}}

Shrinking .....(5 time(s))
{0,{set,0,0,1,0,0,0,undefined,undefined}}
">>

proper_tests:1035: adts_test_...*failed*
in function proper_tests:'-adts_test_/0-fun-8-'/0 (test/proper_tests.erl, line 1035)
in call from proper_tests:'-adts_test_/0-fun-13-'/0 (test/proper_tests.erl, line 1035)
**error:{assertMatch,[{module,proper_tests},
              {line,1035},
              {expression,"proper : quickcheck ( ? FORALL ( { X , Y , D } , { integer ( ) , float ( ) , dict ( integer ( ) , float ( ) ) } , dict : fetch ( X , dict : store ( X , Y , eval ( D ) ) ) =:= Y ) , [ 30 ] )"},
              {pattern,"true"},
              {value,false}]}
  output:<<"!
Failed: After 1 test(s).
An exception was raised: error:badarg.
Stacktrace: [{erlang,phash,[1,0],[]},
             {dict,get_slot,2,[{file,"dict.erl"},{line,390}]},
             {dict,store,3,[{file,"dict.erl"},{line,180}]}].
{1,0.6556127625185277,{dict,0,1,0,0,0,0,{},{}}}

Shrinking ....(4 time(s))
{0,0.0,{dict,0,0,0,0,0,0,undefined,{}}}
">>

=======================================================
  Failed: 2.  Skipped: 0.  Passed: 509.
ERROR: One or more eunit tests failed.
make: *** [tests] Error 1

## conditions:
[root@fb5898e01c12 proper]# erl --version
Erlang/OTP 18 [erts-7.1] [source-2882b0c] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

[root@fb5898e01c12 proper]# cat /etc/redhat-release
CentOS release 6.6 (Final)

**Comment by kostis** [comment]
Thanks for your report. However, this is not a CentOS issue, but a general (known) problem of using auto-ADTs (generating instances of built-in opaque types) in 18.0 and 18.1. Fixing this on our TODO list. Other than that, PropEr works without any other problems in 18.x (and on CentOS) as far as we know.

**Comment by ifn** [comment]
Thanks! I've changed the title.

**Comment by StoneCypher** [comment]
Happens in 18.2.1/mac also (huge surprise)

**Comment by kostis** [comment]
We have fixed PropEr and now all the tests should again be running on all OTP releases it supports (R15-x to 18.x).   We will also soon create a new tagged version of PropEr.

**Comment by StoneCypher** [comment]
Thanks :+1:
