### ISSUE TITLE
Questions on statem's next_state

### ISSUE THREAD

**Issue by ferd** [manopapad/proper#110]
Regarding `next_state` in statem tests, I have a question regarding the use of both symbolic calls and non-symbolic calls.

One of the things I'm toying with right now is writing a toy Erlang test suite of a python program for a local meetup, about a very simple ATM. One of my clauses, to withdraw money, looks a bit like this:

```erlang
  postcondition(#state{user=User, accounts=Accs},
                {call, _, withdraw, [Amount]}, Res) ->
      %% Rules here
      %% - the amount matches what the model tracks
      %% - exceptions if the amount is greater than what the account
      %%   balance allows
      #{User := Balance} = Accs,
      if Balance < Amount ->
           Res =:= {error, "overdraft forbidden"}
       ; Balance >= Amount ->
           Res =:= {ok, Balance - Amount}
      end;
```

Now the problem comes when I have to update the state for `next_state`:

```erlang
next_state(S=#state{user=User, accounts=Accs}, Res, {call, _, withdraw, _}) ->
    case Res of
        {ok, Val} -> S#state{accounts=Accs#{User => Val}};
        {error, _} -> S
    end;
```
This visibly cannot work since many calls will come in with `Res = {var, SomeInteger}`, the symbolic value expected.

On the other hand, determining whether I get `ok` or `error` as a first tuple element now needs to be something horribly bad like

```erlang
-export([decide_withdraw/2]).

% ...

next_state(S=#state{user=User, accounts=Accs}, Res, {call, _, withdraw, _}) ->
    #{User := Current} = Accs, 
    S#state{accounts=Accs#{User => {call, ?MODULE, decide_withdraw, [Current, Res]}}};

% ...

decide_withdraw(_, {ok, Res}) -> Res;
decide_withdraw(Current, {error, _}) -> Current
```

Other alternatives seem to be to reimplement 90% of the postcondition by hand, with symbolic calls and all, except that without the ability to know the current `Amount` (because it may be symbolic), we're still forced to defer these operations through third functions like above, and export it, and give it a name.

What I found is that it appears I can safely ignore the symbolic values to eat my cake and have it:

```erlang
  next_state(S=#state{user=User, accounts=Accs}, {ok, Res}, {call, _, withdraw, _}) ->
      %% if the withdrawal worked we track the new balance, as `Res' is validated by the postcondition
      S#state{accounts=Accs#{User => Res}};
  next_state(S=#state{}, {error, _}, {call, _, withdraw, _}) ->
      %% withdrawal failed, ignore
      S;
  next_state(State, _Res, {call, _Mod, _Fun, _Args}) ->
      %% catch-all clause, conveniently ignores all symbolic runs
      NewState = State,
      NewState.
```
This conveniently ignores symbolic values since none of them would ever return `{ok, _}` nor `{error, _}`. Once the `next_state` call is run after the postcondition succeeds, things work fine.

So given that context, my questions are:

1. Is there any downside to this approach (aside from having to *always* wrap my results)? Will I break anything?
2. Is there a better approach that doesn't require me to play with exports and all that garbage?
3. Why does PropEr even need to run the `next_state/3` callback with symbolic values if it ends up calling them again with the exact value and apparently ignoring all the symbolic runs?

**Comment by ferd** [comment]
Otherwise, I'm considering an alternative such as:

```erlang
next_state(State, Res, Call) -> {call, ?MODULE, next_state_, [State, Res, Call]}
next_state_(...) -> % actual stuff I would put in `next_state/3`
```
Which would appear to solve all my problems if at the very least, PropEr manages to evaluate arguments in the order they should logically be evaluated in symbolic calls.

**Comment by eiriniar** [comment]
Apologies for the delayed reply. In case this is still of interest to you, here are some answers:

1. Your approach (i.e. not updating the state during command generation) will not break anything, as long as you do not have any preconditions that depend on the current state.
2. I am not aware of a different approach.
3. PropEr generates _valid_ command sequences, where all commands satisfy the corresponding preconditions (as specified via the `precondition/2` callback). Since (a non-trivial)  `precondition/2` most probably depends on the current state of the abstract state machine, the current state needs to be updated accordingly during command generation time (using symbolic values).

**Comment by ferd** [comment]
Yeah, long term, the way I've decided to go at it is to take an approach where determinism plays a bigger role; from the inputs I have (since the generators' values appears to always be usable in `next_state` (whereas the `Res` value wouldn't be), I must be able to predict the output I would have from the model itself.

I have found it more convenient to rely on model state within pre-conditions and reduce my ability to explore non-deterministic spaces than the opposite; especially since the ability to refer to previously-inserted or removed values (for example) allows more efficient state space exploration in most cases I've played with so far.
