### ISSUE TITLE
Tag for new version?  Last tagged version v1.1 was in 2013

### ISSUE THREAD

**Issue by linearregression** [manopapad/proper#114]
Is there a new version coming?
The last tagged version was in 2013 for v1.1...?

**Comment by rbarlow** [comment]
This would be great for https://github.com/manopapad/proper/issues/100

**Comment by mrallen1** [comment]
+1

**Comment by lemenkov** [comment]
That would be great! Please tag a new version, @manopapad!

**Comment by kostis** [comment]
Yesterday finally found some time to complete the last set of changes required for PropEr to also compile without warnings and work correctly also on the upcoming 19.0.  I think we are now ready to go and I will tag the current master as version 1.2.  Thanks a lot for your patience!

**Comment by kostis** [comment]
PropEr v1.2 is ready (https://github.com/manopapad/proper/releases).  Enjoy!

**Comment by lemenkov** [comment]
@kostis, thanks!

**Comment by mrallen1** [comment]
Thanks for this!
