### ISSUE TITLE
Failing test: max_size_test

### ISSUE THREAD

**Issue by candrews** [manopapad/proper#129]
Running the unit tests results in this test failing:
```
    proper_tests: max_size_test...*failed*
in function proper_tests:'-max_size_test/0-fun-3-'/2 (test/proper_tests.erl, line 1209)
**error:{assert,[{module,proper_tests},
         {line,1209},
         {expression,"2 * Ts >= Tb"},
         {expected,true},
         {value,false}]}
```

Here's my erlang version info:
```
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
```

I'm using PropEr version 1.2.

**Comment by kostis** [comment]
Unless this failure happens consistently (e.g. 3-4 times in a row) do not worry about it, especially if you are running on a VM environment of some sort.  This particular test checks the timing behavior of PropEr (`Ts` and `Tb` are time values), which occasionally is a bit flaky.

**Comment by kostis** [comment]
I will close this issue.  Reopen it again if you experience consistent failures of this test.
