### ISSUE TITLE
Unit tests fail with proper-1.2+

### ISSUE THREAD

**Issue by aidecoe** [manopapad/proper#145]
```
==> proper (eunit)                                                                                                                                              [70/9550]
proper_tests:700: simple_types_test_...*failed*
in function proper_tests:assert_can_translate/2 (test/proper_tests.erl, line 237)
in call from proper_tests:assert_type_works/2 (test/proper_tests.erl, line 223)
**error:{badmatch,
    {error,
        {cant_load_code,proper_tests,
            {{invalid_chunk,<<70,79,82,49,0,6,102,164,66,...>>,"Abst"},
             {cant_compile_source_file,
                 [{"/home/aidecoe/src/dev-erlang/proper/.eunit/proper_tests.erl",
                   [{28,epp,{include,...}},
                    {29,epp,{...}},
                    {283,epp,...},
                    {381,...},
                    {...}|...]},
                  {"/home/aidecoe/src/dev-erlang/proper/.eunit/proper_tests.erl",
                   [{487,erl_lint,{...}},
                    {487,erl_lint,...},
                    {488,...},
                    {...}|...]}]}}}}}
  output:<<"">>

proper_tests:700: simple_types_test_...*failed*
in function proper_tests:assert_can_translate/2 (test/proper_tests.erl, line 237)
in call from proper_tests:assert_type_works/2 (test/proper_tests.erl, line 223)
**error:{badmatch,
    {error,
        {cant_load_code,proper_tests,
            {{invalid_chunk,<<70,79,82,49,0,6,102,164,66,...>>,"Abst"},
             {cant_compile_source_file,
                 [{"/home/aidecoe/src/dev-erlang/proper/.eunit/proper_tests.erl",
                   [{28,epp,{include,...}},
                    {29,epp,{...}},
                    {283,epp,...},
                    {381,...},
                    {...}|...]},
                  {"/home/aidecoe/src/dev-erlang/proper/.eunit/proper_tests.erl",
                   [{487,erl_lint,{...}},
                    {487,erl_lint,...},
                    {488,...},
                    {...}|...]}]}}}}}
  output:<<"">>
```
...and lots of these...

```
=======================================================
  Failed: 133.  Skipped: 0.  Passed: 415.
ERROR: One or more eunit tests failed.
make: *** [Makefile:58: tests] Error 1
```

See [full output](http://www37.zippyshare.com/v/jjbxQODA/file.html). I had to upload it somewhere else, because log has >30 MiB and GitHub doesn't accept compressed files.

I have tried running with Erlang 18.3 and Erlang 19.2. Same results.

**Comment by kostis** [comment]
AFAIK, the tests do not fail on current `master'.  See also [a recent Travis build](https://travis-ci.org/manopapad/proper).  Admittedly, it has been a while since we've last tried PropEr 1.2, but it seems that your build fails due to not being able to load the test file, not due to tests producing unexpected results.  Can you try to re-compile and/or use the `master` branch and see what happens?

**Comment by aidecoe** [comment]
Thanks for quick reply. I've noticed that it has problem with loading test file, but that file is there and has some content.

I'd include that file, but GitHub reports `Something went really wrong, and we can’t process that file.`...

**Comment by aidecoe** [comment]
I've uploaded it again to zippyshare: http://www47.zippyshare.com/v/rUxq9Op4/file.html

**Comment by kostis** [comment]
Please start from a clean clone of PropEr, preferably from the current `master`, and see if you can run the tests or not and whether you get the same problem there or not. Finding out why this file that you have somehow generated is corrupt and cannot be loaded in your system is not the proper thing to do here. There are a million reasons why that `.beam` file can be corrupted and none of them has to do with PropEr.

**Comment by aidecoe** [comment]
I've done a fresh clone followed by `make && make tests`. Same results. I have Erlang 19.2 configured with following options:

```
./configure --disable-silent-rules --enable-threads --disable-sctp --disable-systemd --disable-hipe --with-ssl=/usr --enable-dynamic-ssl-lib --disable-kernel-poll --enable-smp-support --disable-dirty-schedulers
```

(I have skipped `--prefix` and other paths.)

**Comment by kostis** [comment]
Fresh clone of 1.2 or of the current master? Also, what sort of platform/OS are you running on?

**Comment by aidecoe** [comment]
master. OS is Gentoo. I have tried both x86 and amd64.

**Comment by kostis** [comment]
I am sorry but I cannot reproduce this issue in anything I've tried. (However, I do not have access to a Gentoo machine and I do not configure with all these options.)

Can it be that you have some strange compiler options in your environment variables, e.g. in your `ERL_COMPILER_OPTIONS`?  From the crash you get, it looks like the "Abst" (Abstract) code chunk of your .beam file is corrupt.

I will keep this issue open for a while, but I do not see much that can be done about it if it cannot be reproduced / confirmed by somebody else.

**Comment by aidecoe** [comment]
I don't have anything like that set... But that gives at least some clue there should be something specific about environment. Although it's hard to say what. I have checked that on one of the machines I haven't upgraded Erlang since time when PropEr tests pass. Some other libs where upgraded but PropEr doesn't really have deps. Hopefully I will figure out sooner or later what's going on. Thank you!

**Comment by aidecoe** [comment]
I have hit the issue in some other packages, so it seems it's not specific to proper.
