### ISSUE TITLE
Warning about get_stacktrace/0 on OTP 20

### ISSUE THREAD

**Issue by NobbZ** [manopapad/proper#153]
```plain
/home/nmelzer/projects/erlang/hfe/_build/test/lib/proper/src/proper_typeserver.erl:553: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
/home/nmelzer/projects/erlang/hfe/_build/test/lib/proper/src/proper_typeserver.erl:556: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
_build/test/lib/proper/src/proper_typeserver.erl:553: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
_build/test/lib/proper/src/proper_typeserver.erl:556: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
```

This warnings occur when compiling 1.2.0 from hex on OTP 20.

**Comment by kostis** [comment]
Thanks for pointing out this, but actually this is a harmless warning.  In any case, we cannot really change the code of a tagged version, can we?  The only possibility to shut off this warning is to release a new tagged version from the current master branch.

**Comment by NobbZ** [comment]
I never consider warnings as harmless, especially not when they tell me that it might break in a future version.

And yes, making a new release is probably the only way to fix that.

But that's what releases are for, fixing old bugs, warnings and also introducing new features.

**Comment by kostis** [comment]
> I never consider warnings as harmless, especially not when they tell me that it might break in a future version.

It's harmless -- and will continue to be so for at least two more years in the future.  Trust me.

**Comment by NobbZ** [comment]
Yes, we have 2 years to fix it. Still, we have to fix it.

Deprecation warnings are there for a reason, and the reason is not that they want to be ignored…

**Comment by kostis** [comment]
> Yes, we have 2 years to fix it. Still, we have to fix it.

Just in case it's not clear to you, this is already fixed in the `master` branch. If this particular warning really bothers you, you can use this version.

I am closing the issue.

**Comment by NobbZ** [comment]
Why don't you tell this right from the start?

**Comment by kostis** [comment]
> Why don't you tell this right from the start?

I think I did.  You reported an issue for tagged version 1.2.0 and I wrote:

> ... we cannot really change the code of a tagged version, can we? The only possibility to shut off this warning is to release a new tagged version from the current master branch.

Apologies if it was too cryptic.
