### ISSUE TITLE
proper:quickcheck/1 returns missing_type

### ISSUE THREAD

**Issue by arcusfelis** [manopapad/proper#64]
Test case is called from unit using `proper:quickcheck/1`.
Source was compiled with `debug_info`.
Type `dht_query` is defined inside a module.
```
{error,
                  {typeserver,
                      {missing_type,etorrent_dht_net,{type,dht_query,0}}}}
```

**Comment by kostis** [comment]
Is this issue still valid/interesting or should I close it?

**Comment by kostis** [comment]
I guess there will not be a code pointer or self-contained test that shows this. I am therefore considering it not an issue anymore.  Open a new issue if this is still relevant.
