### ISSUE TITLE
dict/0, set/0, queue/0, gb_tree/0, gb_set/0, array/0 deprecated

### ISSUE THREAD

**Issue by StoneCypher** [manopapad/proper#98]
On compiling proper under r17, one gets a wall of messages of the form `/gigantic/path/lib/proper/src/proper_typeserver.erl:235: Warning: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2`

I assume you're already aware of this and have accounted for it in r18, but I'm filing this just in case, because I don't see any closed tickets about this.

**Comment by kostis** [comment]
<rant>
Given that 18.0 is not yet released, I am not sure I understand the point of this issue.

It's pretty clear that when 18.0 will be released some action needs to happen, but having an open issue about it does not make it any more or less likely that this action will actually occur.  It just adds some more work (remembering to close this issue) to those who will perform this action...  Not sure how helpful this is.
</rant>

Anyway, the real problem with the action that needs to be taken is not making the code compile under 18.0, which can be done in two minutes, but making the change in a way that PropEr can still continue to work in Erlang/OTP releases prior to 17.0.  But given that PropEr needs to also support maps at some point, perhaps it is inevitable to cross the line where releases prior to 17.0 will not be supported any more by the 'main' branch when 18.0 is released.

**Comment by StoneCypher** [comment]
k i just wanted to make sure you knew.  wasn't sure if the library was actively maintained.

**Comment by kostis** [comment]
Turns out that I could use the infrastructure that the `write_compile_flags` escript provides, to modify PropEr's code in a way that these warnings are eliminated and the code still compiles in releases prior to 17.0.  I consider the issue addressed and I will close it.

**Comment by StoneCypher** [comment]
Thanks :)
